---
name: Run Unit Tests

on: 
  push:
    branches:
      - master

jobs:
  build:
    name: Build Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: echo Continue here...
