---
name: Run Unit Tests

on: 
  push:
    branches:
      - master

jobs:
  test:
    name: Test Application
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
